version: "3.9"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  weather:
    build:
      context: .
      dockerfile: Dockerfile.weather
  news:
    build:
      context: .
      dockerfile: Dockerfile.news
